# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # WeatherPackage via local path (for development)
  # Alternatively, you can use the GitHub repo URL
  pod 'WeatherPackage', :path => '../../'
  
  # Or use GitHub directly:
  # pod 'WeatherPackage', :git => 'https://github.com/remcozut/WeatherPackage.git'

end
